### ISSUE TITLE
Does not Build with Java 14 and Gradle 2.10

### ISSUE THREAD

**Issue by jchamlin** [Simsilica/SimMath#2]
SimMath uses Gradle 2.10, which doesn't recognize Java 14. In order to get the project built I had to update the `gradle-wrapper.properties` and set `distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-bin.zip`. It successfully built and installed with Gradle 6.3.

Also, the reason I had to build and install SimMath is because I'm trying to build Subspace-Infinity, which uses SimMath 1.4.1-SNAPSHOT, and 1.4.1 is not published. Also, Subspace-Infinity looks like it requires a bunch of dependencies on MOSS that aren't published anywhere.

```
    implementation project(":mphys")
    implementation project(":mblock")
    implementation project(":mblock-physb")
    implementation project(":sio2-mblock")
    implementation project(":sio2-mphys")
    implementation project(":mworld")

include ":mphys"
project(":mphys").projectDir = file("../pspeed42/moss/mphys")

include ":mblock"
project(":mblock").projectDir = file("../pspeed42/moss/mblock")
include ":mblock-physb"
project(":mblock-physb").projectDir = file("../pspeed42/moss/mblock-physb")
include ":sio2-mblock"
project(":sio2-mblock").projectDir = file("../pspeed42/moss/sio2-mblock")
include ":sio2-mphys"
project(":sio2-mphys").projectDir = file("../pspeed42/moss/sio2-mphys")
include ":mworld"
project(":mworld").projectDir = file("../pspeed42/moss/mworld")
```

I found information about MOSS here: http://www.simsilica.com/the-moss-initiative/

Any way I can get access to that code so I can try out building and running Subspace-Infinity? I just want to see a game written with jMonkeyEngine and LWJDL to see how it works. I am interested in seeing what's possible for game-engine building with Java, instead of the usual C/C++ or C#+Infinity.

Thanks!

-J.C.

**Comment by pspeed42** [comment]
Sorry you were having trouble building.  I'm still personally stuck on Java 8 for a variety of reasons and so I don't get to test stuff with the "new hotness".

MOSS is not yet released to the public.  I think the author of Subspace is one of my patrons on patreon and so has early access to it.  The library is still in flux and is too hard to publicly support in its current stage... but I offer it as a perk to patrons.

However, there are many jMonkeyEngine games out there that you can take a look at and even some simpler examples.  Some are just the basic beginnings of a game like the sim-ethereal examples here:
https://github.com/Simsilica/Examples
...which have both an Entity System example and a basic POJO game object example.  I'm pretty sure that the first was the partial basis for Subspace-Infinity.  Those sim-eth-es and sim-eth-basic examples are the foundations for creating a real time networked game.

If you look on the jmonkey engine forums or the store there are also other examples, I think.

**Comment by jchamlin** [comment]
I guess you could try upgrading your Gradle wrapper to 6.3 and see if it builds with Java 8. Gradle 6.3 only requires Java 8 or higher.

Thanks for the link to the other examples. I'll check them out.

As far as building Subspace-Infinity, mind if the author puts MOSS into his own private GitHub repo and shares with me? Or can you share it with me?

Thanks.

**Comment by benoit-dubreuil** [comment]
I'll attempt to update the Gradle wrapper version, as I need a version greater than or equal to `3.0` because my IDE doesn't support lower versions.

**Comment by pspeed42** [comment]
Closing this now... the gradle wrapper has been upgraded some time back and SimMath should build with any version of Java after JDK7.
