### ISSUE TITLE
A typo on interface name!

### ISSUE THREAD

**Issue by Ali-RS** [Simsilica/SimMath#3]
Hi

Looks like a typo here. I guess it should be "Filtered", not "Filterd". Of course, will be a breaking change to fix.

https://github.com/Simsilica/SimMath/blob/b428c2516ab64f18936ad62cb6822c80ba548193/src/main/java/com/simsilica/mathd/filter/Filterd.java#L47

**Comment by pspeed42** [comment]
Vec3d, Quatd, Filterd.  No typo.

If I was ever crazy enough to make a float version then it would be called Filterf.

**Comment by Ali-RS** [comment]
Ah, I see. Sorry for the misunderstanding.

**Comment by pspeed42** [comment]
No worries.  Thanks for keeping me own my toes.  Even I had a 5 second panic that I'd checked in a typo in a file name. :)
