### ISSUE TITLE
Update Gradle wrapper's version

### ISSUE THREAD

**Issue by benoit-dubreuil** [Simsilica/SimMath#5]
### Original intent
> **Update the Gradle wrapper's version**
Currently, the Gradle wrapper version used is `2.10`. I'd like to use the latest version, which is Gradle `7.1.1`. It is necessary, as my IDE does not support Gradle versions that old. Also, newer versions allow the use of newer JDKs. See the the following GitHub issue : https://github.com/Simsilica/SimMath/issues/2#issuecomment-896918407

### References
See the forum discussion : https://hub.jmonkeyengine.org/t/simmath-vec3i-contribution/44833

Related to the following issues : #2

**Comment by pspeed42** [comment]
Closing this as the gradle wrapper was updated some time back to 7.4.2.
